### ISSUE TITLE
Needs more Cowbell

### ISSUE THREAD

**Issue by jmenglis** [sbrunswig/fourdab#1]
I think this project needs more cowbell :smile:

**Comment by jmenglis** [comment]
I think we need more of this.

![image](https://user-images.githubusercontent.com/13577271/39011133-42c94280-43d6-11e8-9653-794e8c56f8c4.png)

**Comment by Sonic12040** [comment]
# Cowbell Requirements

There is an appropriate amount of cowbell on each and every page. I know, because I'm Bruce Dickinson.
